spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "@Aa123456"
server:
  port: 8081
rocketmq:
  name-server: 8.210.250.29:9876
  producer:
    group: my-group           # 生产者组名
logging:
  level:
    org.apache.rocketmq: DEBUG

